# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/gitProject/v5_EL/electronic_load_last.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ELECTRONICLOAD(object):
    def setupUi(self, ELECTRONICLOAD):
        ELECTRONICLOAD.setObjectName("ELECTRONICLOAD")
        ELECTRONICLOAD.resize(1114, 800)
        ELECTRONICLOAD.setSizeGripEnabled(True)
        self.pushButton = QtWidgets.QPushButton(ELECTRONICLOAD)
        self.pushButton.setGeometry(QtCore.QRect(990, 30, 93, 21))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(ELECTRONICLOAD)
        self.pushButton_2.setGeometry(QtCore.QRect(990, 60, 93, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayoutWidget = QtWidgets.QWidget(ELECTRONICLOAD)
        self.formLayoutWidget.setGeometry(QtCore.QRect(840, 30, 141, 61))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.comboBox_2 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.textBrowser = QtWidgets.QTextBrowser(ELECTRONICLOAD)
        self.textBrowser.setGeometry(QtCore.QRect(830, 140, 261, 111))
        self.textBrowser.setObjectName("textBrowser")
        self.lineEdit = QtWidgets.QLineEdit(ELECTRONICLOAD)
        self.lineEdit.setGeometry(QtCore.QRect(830, 110, 181, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_3 = QtWidgets.QPushButton(ELECTRONICLOAD)
        self.pushButton_3.setGeometry(QtCore.QRect(1020, 110, 71, 21))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_10 = QtWidgets.QLabel(ELECTRONICLOAD)
        self.label_10.setGeometry(QtCore.QRect(830, 330, 251, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setFrameShape(QtWidgets.QFrame.Box)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(ELECTRONICLOAD)
        self.label_11.setGeometry(QtCore.QRect(830, 360, 91, 41))
        self.label_11.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(ELECTRONICLOAD)
        self.label_13.setGeometry(QtCore.QRect(830, 400, 91, 41))
        self.label_13.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_15 = QtWidgets.QLabel(ELECTRONICLOAD)
        self.label_15.setGeometry(QtCore.QRect(830, 440, 91, 41))
        self.label_15.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(ELECTRONICLOAD)
        self.label_16.setGeometry(QtCore.QRect(830, 480, 91, 41))
        self.label_16.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_18 = QtWidgets.QLabel(ELECTRONICLOAD)
        self.label_18.setGeometry(QtCore.QRect(831, 530, 241, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setFrameShape(QtWidgets.QFrame.Box)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_22 = QtWidgets.QLabel(ELECTRONICLOAD)
        self.label_22.setGeometry(QtCore.QRect(830, 560, 91, 41))
        self.label_22.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(ELECTRONICLOAD)
        self.label_23.setGeometry(QtCore.QRect(830, 600, 91, 41))
        self.label_23.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(ELECTRONICLOAD)
        self.label_24.setGeometry(QtCore.QRect(830, 640, 91, 41))
        self.label_24.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(ELECTRONICLOAD)
        self.label_25.setGeometry(QtCore.QRect(830, 680, 91, 41))
        self.label_25.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(ELECTRONICLOAD)
        self.label_26.setGeometry(QtCore.QRect(830, 720, 91, 41))
        self.label_26.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.label_19 = QtWidgets.QLabel(ELECTRONICLOAD)
        self.label_19.setGeometry(QtCore.QRect(830, 260, 251, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setFrameShape(QtWidgets.QFrame.Box)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_31 = QtWidgets.QLabel(ELECTRONICLOAD)
        self.label_31.setGeometry(QtCore.QRect(830, 290, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setFrameShape(QtWidgets.QFrame.Box)
        self.label_31.setText("")
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(ELECTRONICLOAD)
        self.label_32.setGeometry(QtCore.QRect(920, 360, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setFrameShape(QtWidgets.QFrame.Box)
        self.label_32.setText("")
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(ELECTRONICLOAD)
        self.label_33.setGeometry(QtCore.QRect(920, 400, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setFrameShape(QtWidgets.QFrame.Box)
        self.label_33.setText("")
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.textBrowser_2 = QtWidgets.QTextBrowser(ELECTRONICLOAD)
        self.textBrowser_2.setGeometry(QtCore.QRect(920, 440, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.textBrowser_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(ELECTRONICLOAD)
        self.textBrowser_3.setGeometry(QtCore.QRect(920, 480, 171, 41))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(ELECTRONICLOAD)
        self.textBrowser_4.setGeometry(QtCore.QRect(920, 560, 171, 41))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(ELECTRONICLOAD)
        self.textBrowser_5.setGeometry(QtCore.QRect(920, 600, 171, 41))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser_6 = QtWidgets.QTextBrowser(ELECTRONICLOAD)
        self.textBrowser_6.setGeometry(QtCore.QRect(920, 640, 171, 41))
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.textBrowser_7 = QtWidgets.QTextBrowser(ELECTRONICLOAD)
        self.textBrowser_7.setGeometry(QtCore.QRect(920, 680, 171, 41))
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.textBrowser_8 = QtWidgets.QTextBrowser(ELECTRONICLOAD)
        self.textBrowser_8.setGeometry(QtCore.QRect(920, 720, 171, 41))
        self.textBrowser_8.setObjectName("textBrowser_8")

        self.retranslateUi(ELECTRONICLOAD)
        QtCore.QMetaObject.connectSlotsByName(ELECTRONICLOAD)

    def retranslateUi(self, ELECTRONICLOAD):
        _translate = QtCore.QCoreApplication.translate
        ELECTRONICLOAD.setWindowTitle(_translate("ELECTRONICLOAD", "ELECTRONIC LOAD"))
        self.pushButton.setText(_translate("ELECTRONICLOAD", "CONNECT"))
        self.pushButton_2.setText(_translate("ELECTRONICLOAD", "STOP"))
        self.comboBox.setItemText(0, _translate("ELECTRONICLOAD", "COM4"))
        self.comboBox.setItemText(1, _translate("ELECTRONICLOAD", "COM5"))
        self.comboBox.setItemText(2, _translate("ELECTRONICLOAD", "COM6"))
        self.comboBox.setItemText(3, _translate("ELECTRONICLOAD", "COM7"))
        self.label.setText(_translate("ELECTRONICLOAD", "BaudRate"))
        self.label_2.setText(_translate("ELECTRONICLOAD", "PORT"))
        self.comboBox_2.setItemText(0, _translate("ELECTRONICLOAD", "115200"))
        self.comboBox_2.setItemText(1, _translate("ELECTRONICLOAD", "57600"))
        self.comboBox_2.setItemText(2, _translate("ELECTRONICLOAD", "38400"))
        self.comboBox_2.setItemText(3, _translate("ELECTRONICLOAD", "19200"))
        self.comboBox_2.setItemText(4, _translate("ELECTRONICLOAD", "9600"))
        self.comboBox_2.setItemText(5, _translate("ELECTRONICLOAD", "1200"))
        self.pushButton_3.setText(_translate("ELECTRONICLOAD", "SEND"))
        self.label_10.setText(_translate("ELECTRONICLOAD", "Electronic Load"))
        self.label_11.setText(_translate("ELECTRONICLOAD", "DAC "))
        self.label_13.setText(_translate("ELECTRONICLOAD", "PWM"))
        self.label_15.setText(_translate("ELECTRONICLOAD", "DC CURRENT"))
        self.label_16.setText(_translate("ELECTRONICLOAD", "DC VOLTAGE"))
        self.label_18.setText(_translate("ELECTRONICLOAD", "Efficiency"))
        self.label_22.setText(_translate("ELECTRONICLOAD", "AC CURRENT"))
        self.label_23.setText(_translate("ELECTRONICLOAD", "AC VOLTAGE"))
        self.label_24.setText(_translate("ELECTRONICLOAD", "DC CURRENT"))
        self.label_25.setText(_translate("ELECTRONICLOAD", "DC VOLTAGE"))
        self.label_26.setText(_translate("ELECTRONICLOAD", "NTC"))
        self.label_19.setText(_translate("ELECTRONICLOAD", "MODE"))
        self.textBrowser_2.setHtml(_translate("ELECTRONICLOAD", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("ELECTRONICLOAD", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser_4.setHtml(_translate("ELECTRONICLOAD", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser_5.setHtml(_translate("ELECTRONICLOAD", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser_6.setHtml(_translate("ELECTRONICLOAD", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser_7.setHtml(_translate("ELECTRONICLOAD", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser_8.setHtml(_translate("ELECTRONICLOAD", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))

